
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}
spring.cloud.aws.region.static=us-east-1


spring.cloud.aws.stack.auto=false
spring.cloud.aws.region.auto=false
cloud.aws.region.auto=false
spring.cloud.aws.sns.enabled=false


aws.sqs.queue.pedido=T02N-PEDRO-HENRIQUE-DE-ALMEIDA-MARQUES.fifo


spring.datasource.url=jdbc:h2:mem:arq_software
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always