spring.datasource.url=jdbc:h2:mem:arq_software
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.sql.init.mode=always

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=AKIAXZXQFI7SQXVZKURA
spring.cloud.aws.credentials.secret-key=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

aws.sqs.queue.pedido=T02N-PEDRO-HENRIQUE-DE-ALMEIDA-MARQUES.fifo
queue.order-events=T02N-PEDRO-HENRIQUE-DE-ALMEIDA-MARQUES.fifo

#aws.sqs.queue.saida-estoque=SQS-SAIDA-ESTOQUE.fifo
#aws.sqs.queue.entrada-estoque=SQS-ENTRADA-ESTOQUE.fifo